"""Curated US equity analyst and institution directory.

The tickers in this file are representative public research themes or commonly
associated holdings, not a claim of current portfolio ownership.  Keep this
module data-only so the UI, scoring engine, and future data providers can share
the same directory.
"""

from __future__ import annotations

from typing import Final


ANALYST_DIRECTORY: Final[list[dict]] = [
    {
        "id": "howard_marks",
        "name": "Howard Marks",
        "org": "Oaktree Capital",
        "style_tags": ["Value", "Macro"],
        "representative_tickers": ["OAK", "HYG", "LQD"],
        "focus": "信用周期、風險評估、宏觀市場備忘錄",
        "platform": "Oaktree Capital / Bloomberg",
        "stance": "謹慎",
        "stance_color": "#FF8C00",
        "rep": 5,
        "years_active": 30,
        "type": "機構級別分析師",
        "rationale": "以信用週期與下行風險管理聞名，重視安全邊際。",
    },
    {
        "id": "cathie_wood",
        "name": "Cathie Wood",
        "org": "ARK Invest",
        "style_tags": ["Tech", "Growth"],
        "representative_tickers": ["ARKK", "TSLA", "NVDA"],
        "focus": "顛覆性創新、AI、基因組學、加密貨幣",
        "platform": "ARK ETFs / X @CathieDWood",
        "stance": "積極做多",
        "stance_color": "#00CC44",
        "rep": 4,
        "years_active": 15,
        "type": "機構級別分析師",
        "rationale": "公開持倉透明，專注長期創新主題與技術拐點。",
    },
    {
        "id": "adam_khoo",
        "name": "Adam Khoo",
        "org": "Adam Khoo Learning Technologies",
        "style_tags": ["Value", "Technical"],
        "representative_tickers": ["AAPL", "MSFT", "SPY"],
        "focus": "價值投資、技術分析結合、波段操作",
        "platform": "YouTube / 課程平台",
        "stance": "中性偏多",
        "stance_color": "#0066CC",
        "rep": 4,
        "years_active": 12,
        "type": "長期價值投資專家",
        "rationale": "把基本面、估值與趨勢訊號整合成可執行框架。",
    },
    {
        "id": "jeremy_siegel",
        "name": "Jeremy Siegel",
        "org": "Wharton School / WisdomTree",
        "style_tags": ["Value", "Income", "Macro"],
        "representative_tickers": ["VIG", "SCHD", "SPY"],
        "focus": "長期股票市場、股息成長、退休投資組合",
        "platform": "CNBC / Bloomberg TV",
        "stance": "長期樂觀",
        "stance_color": "#00CC44",
        "rep": 5,
        "years_active": 35,
        "type": "學術型市場分析師",
        "rationale": "以長期資料研究股票複利、股息與估值週期。",
    },
    {
        "id": "michael_burry",
        "name": "Michael Burry",
        "org": "Scion Asset Management",
        "style_tags": ["Value", "Macro", "Contrarian"],
        "representative_tickers": ["GEO", "SHV", "SQQQ"],
        "focus": "逆向投資、系統性風險、做空策略",
        "platform": "SEC 13F / 公開訪談",
        "stance": "偏空／逆向",
        "stance_color": "#FF4B4B",
        "rep": 4,
        "years_active": 20,
        "type": "逆向價值投資者",
        "rationale": "重視資產負債表、估值錯價與系統性風險。",
    },
    {
        "id": "joseph_carlson",
        "name": "Joseph Carlson",
        "org": "Joseph Carlson Show",
        "style_tags": ["Value", "Income", "Growth"],
        "representative_tickers": ["MSFT", "AAPL", "V"],
        "focus": "成長股、股息再投資、個人持倉透明化",
        "platform": "YouTube",
        "stance": "長期持有",
        "stance_color": "#0066CC",
        "rep": 4,
        "years_active": 8,
        "type": "公開持倉投資者",
        "rationale": "以現金流、股息再投資與長期持有為核心。",
    },
    {
        "id": "seeking_alpha_quant",
        "name": "Seeking Alpha Quant",
        "org": "Seeking Alpha",
        "style_tags": ["Quant", "Value", "Growth"],
        "representative_tickers": ["NVDA", "AAPL", "META"],
        "focus": "量化篩股、因子投資、財報分析",
        "platform": "seekingalpha.com",
        "stance": "數據驅動",
        "stance_color": "#6600CC",
        "rep": 5,
        "years_active": 15,
        "type": "專業財經數據平台",
        "rationale": "用估值、成長、獲利與動能因子做系統化比較。",
    },
    {
        "id": "wsj_markets",
        "name": "WSJ Markets Desk",
        "org": "Wall Street Journal",
        "style_tags": ["Macro", "Quality"],
        "representative_tickers": ["MSFT", "GOOGL", "META"],
        "focus": "宏觀政策、企業盈利、市場結構分析",
        "platform": "WSJ / 公開市場報導",
        "stance": "中性報導",
        "stance_color": "#8B949E",
        "rep": 5,
        "years_active": 40,
        "type": "專業財經媒體",
        "rationale": "追蹤政策、產業與企業財報的交叉影響。",
    },
    {
        "id": "warren_buffett",
        "name": "Warren Buffett",
        "org": "Berkshire Hathaway",
        "style_tags": ["Value", "Quality", "Income"],
        "representative_tickers": ["BRK-B", "AAPL", "KO"],
        "focus": "護城河、合理估值、長期複利",
        "platform": "Berkshire Hathaway letters",
        "stance": "長期價值",
        "stance_color": "#00CC44",
        "rep": 5,
        "years_active": 60,
        "type": "長期價值投資者",
        "rationale": "以高品質企業、資本配置與長期持有著稱。",
    },
    {
        "id": "charlie_munger",
        "name": "Charlie Munger",
        "org": "Berkshire Hathaway",
        "style_tags": ["Value", "Quality"],
        "representative_tickers": ["BRK-B", "COST", "AAPL"],
        "focus": "跨學科思考、品質企業、反向激勵",
        "platform": "公開演講 / Berkshire",
        "stance": "品質優先",
        "stance_color": "#00CC44",
        "rep": 5,
        "years_active": 55,
        "type": "長期價值投資者",
        "rationale": "強調避免愚蠢錯誤、理解商業品質與管理層。",
    },
    {
        "id": "stanley_druckenmiller",
        "name": "Stanley Druckenmiller",
        "org": "Duquesne Family Office",
        "style_tags": ["Macro", "Growth", "Momentum"],
        "representative_tickers": ["NVDA", "MSFT", "QQQ"],
        "focus": "總體週期、流動性、集中高確信交易",
        "platform": "公開訪談 / 投資論壇",
        "stance": "趨勢跟隨",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 40,
        "type": "宏觀交易者",
        "rationale": "結合宏觀流動性與個股盈利動能做高確信配置。",
    },
    {
        "id": "david_tepper",
        "name": "David Tepper",
        "org": "Appaloosa Management",
        "style_tags": ["Macro", "Value", "Contrarian"],
        "representative_tickers": ["AMZN", "META", "QQQ"],
        "focus": "宏觀資產配置、困境資產、政策週期",
        "platform": "CNBC / 公開訪談",
        "stance": "靈活逆向",
        "stance_color": "#FFD700",
        "rep": 5,
        "years_active": 35,
        "type": "宏觀對沖基金經理",
        "rationale": "善於在利率、政策與估值變化中尋找錯價。",
    },
    {
        "id": "bill_ackman",
        "name": "Bill Ackman",
        "org": "Pershing Square",
        "style_tags": ["Value", "Quality", "Activist"],
        "representative_tickers": ["CMG", "HLT", "GOOG"],
        "focus": "高品質集中投資、品牌護城河、股東行動",
        "platform": "Pershing Square letters",
        "stance": "集中持有",
        "stance_color": "#00CC44",
        "rep": 4,
        "years_active": 25,
        "type": "集中價值投資者",
        "rationale": "偏好可預測現金流、強品牌與長期資本回報。",
    },
    {
        "id": "seth_klarman",
        "name": "Seth Klarman",
        "org": "The Baupost Group",
        "style_tags": ["Value", "Contrarian"],
        "representative_tickers": ["GOOG", "EBAY", "WBD"],
        "focus": "深度價值、困境資產、安全邊際",
        "platform": "Baupost letters / Margin of Safety",
        "stance": "防守價值",
        "stance_color": "#FF8C00",
        "rep": 5,
        "years_active": 40,
        "type": "深度價值投資者",
        "rationale": "嚴格要求安全邊際與下行保護，重視耐心。",
    },
    {
        "id": "joel_greenblatt",
        "name": "Joel Greenblatt",
        "org": "Gotham Asset Management",
        "style_tags": ["Value", "Quant"],
        "representative_tickers": ["SPY", "VTV", "GILD"],
        "focus": "Magic Formula、資本回報率、盈利殖利率",
        "platform": "Gotham / 投資著作",
        "stance": "規則化價值",
        "stance_color": "#6600CC",
        "rep": 5,
        "years_active": 35,
        "type": "量化價值投資者",
        "rationale": "將高資本回報與合理估值結合成可重複流程。",
    },
    {
        "id": "mohnish_pabrai",
        "name": "Mohnish Pabrai",
        "org": "Pabrai Funds",
        "style_tags": ["Value", "Quality"],
        "representative_tickers": ["MU", "GOOG", "AMR"],
        "focus": "集中價值、複製優秀投資、下行保護",
        "platform": "Pabrai Funds / 公開演講",
        "stance": "長期價值",
        "stance_color": "#00CC44",
        "rep": 4,
        "years_active": 25,
        "type": "集中價值投資者",
        "rationale": "尋找高勝率、低下行風險且能長期複利的標的。",
    },
    {
        "id": "aswath_damodaran",
        "name": "Aswath Damodaran",
        "org": "NYU Stern",
        "style_tags": ["Value", "Quant", "Macro"],
        "representative_tickers": ["SPY", "AAPL", "MSFT"],
        "focus": "現金流折現、估值模型、風險溢價",
        "platform": "NYU Stern / Damodaran Online",
        "stance": "估值中性",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 35,
        "type": "估值學者",
        "rationale": "公開估值資料與模型，適合做基本面估值校準。",
    },
    {
        "id": "tom_lee",
        "name": "Tom Lee",
        "org": "Fundstrat Global Advisors",
        "style_tags": ["Macro", "Growth", "Momentum"],
        "representative_tickers": ["SPY", "QQQ", "NVDA"],
        "focus": "市場週期、指數目標、科技與加密資產",
        "platform": "Fundstrat / CNBC",
        "stance": "策略偏多",
        "stance_color": "#00CC44",
        "rep": 4,
        "years_active": 25,
        "type": "策略師",
        "rationale": "以盈利、流動性和市場廣度建立指數與產業觀點。",
    },
    {
        "id": "dan_ives",
        "name": "Dan Ives",
        "org": "Wedbush Securities",
        "style_tags": ["Tech", "Growth"],
        "representative_tickers": ["TSLA", "AAPL", "MSFT"],
        "focus": "軟體、AI、電動車與科技產業競爭",
        "platform": "Wedbush / CNBC",
        "stance": "科技成長",
        "stance_color": "#00D4FF",
        "rep": 4,
        "years_active": 25,
        "type": "科技產業分析師",
        "rationale": "聚焦產品週期、平台轉型與科技資本支出。",
    },
    {
        "id": "gene_munster",
        "name": "Gene Munster",
        "org": "Deepwater Asset Management",
        "style_tags": ["Tech", "Growth", "AI"],
        "representative_tickers": ["AAPL", "NVDA", "TSLA"],
        "focus": "AI、消費科技、平台企業與創新週期",
        "platform": "Deepwater / 公開研究",
        "stance": "創新成長",
        "stance_color": "#00D4FF",
        "rep": 4,
        "years_active": 25,
        "type": "科技研究者",
        "rationale": "長期追蹤消費科技採用率與新興平台商業模式。",
    },
    {
        "id": "liz_ann_sonders",
        "name": "Liz Ann Sonders",
        "org": "Charles Schwab",
        "style_tags": ["Macro", "Quality"],
        "representative_tickers": ["SPY", "SCHD", "IWM"],
        "focus": "市場廣度、景氣週期、股票與債券配置",
        "platform": "Charles Schwab / 公開研究",
        "stance": "週期觀察",
        "stance_color": "#FFD700",
        "rep": 5,
        "years_active": 30,
        "type": "市場策略師",
        "rationale": "將市場廣度、經濟週期與投資人情緒結合。",
    },
    {
        "id": "ed_yardeni",
        "name": "Ed Yardeni",
        "org": "Yardeni Research",
        "style_tags": ["Macro", "Value"],
        "representative_tickers": ["SPY", "XLI", "XLF"],
        "focus": "全球經濟、盈利週期、利率與股市估值",
        "platform": "Yardeni Research",
        "stance": "宏觀研究",
        "stance_color": "#FFD700",
        "rep": 5,
        "years_active": 40,
        "type": "宏觀經濟學家",
        "rationale": "用盈利預期、利率與全球景氣週期解讀市場。",
    },
    {
        "id": "goldman_global_research",
        "name": "Goldman Sachs Global Investment Research",
        "org": "Goldman Sachs",
        "style_tags": ["Macro", "Quant", "Quality"],
        "representative_tickers": ["SPY", "QQQ", "XLF"],
        "focus": "全球宏觀、產業配置、盈利與因子研究",
        "platform": "Goldman Sachs Research",
        "stance": "機構研究",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 45,
        "type": "機構研究團隊",
        "rationale": "覆蓋全球經濟、產業與量化因子，適合做配置參考。",
    },
    {
        "id": "jpmorgan_global_research",
        "name": "J.P. Morgan Global Research",
        "org": "J.P. Morgan",
        "style_tags": ["Macro", "Value", "Quality"],
        "representative_tickers": ["SPY", "JPM", "TLT"],
        "focus": "利率、信用、股票策略與全球資產配置",
        "platform": "J.P. Morgan Research",
        "stance": "機構研究",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 45,
        "type": "機構研究團隊",
        "rationale": "以跨資產研究追蹤政策、信用與股票風險溢價。",
    },
    {
        "id": "blackrock_institute",
        "name": "BlackRock Investment Institute",
        "org": "BlackRock",
        "style_tags": ["Macro", "Income", "Quality"],
        "representative_tickers": ["IVV", "AGG", "SGOV"],
        "focus": "長期主題、資產配置、固定收益與風險管理",
        "platform": "BlackRock Investment Institute",
        "stance": "配置導向",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 15,
        "type": "機構配置研究",
        "rationale": "涵蓋股票、債券與主題投資的長期配置框架。",
    },
    {
        "id": "morgan_stanley_research",
        "name": "Morgan Stanley Research",
        "org": "Morgan Stanley",
        "style_tags": ["Macro", "Tech", "Quality"],
        "representative_tickers": ["SPY", "XLK", "MSFT"],
        "focus": "產業鏈、科技趨勢、全球市場策略",
        "platform": "Morgan Stanley Research",
        "stance": "機構研究",
        "stance_color": "#00D4FF",
        "rep": 5,
        "years_active": 40,
        "type": "機構研究團隊",
        "rationale": "以產業鏈與企業盈利研究支持自上而下配置。",
    },
    {
        "id": "morningstar_quant",
        "name": "Morningstar Quantitative Research",
        "org": "Morningstar",
        "style_tags": ["Quant", "Value", "Quality"],
        "representative_tickers": ["VOO", "VTV", "VIG"],
        "focus": "基金評級、量化因子、估值與品質",
        "platform": "Morningstar",
        "stance": "數據驅動",
        "stance_color": "#6600CC",
        "rep": 5,
        "years_active": 20,
        "type": "量化研究平台",
        "rationale": "以基金、股票與因子評估建立可比較的研究框架。",
    },
]


STYLE_TAGS: Final[list[str]] = [
    "全部",
    "Value",
    "Tech",
    "Macro",
    "Quant",
    "Quality",
    "Growth",
    "Income",
    "Technical",
    "Contrarian",
]
